// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJg3LEJMFKVEaZf6CYniKKhFWDTQuf40g',
    appId: '1:197181622848:web:b4ea976832f5a27d786da5',
    messagingSenderId: '197181622848',
    projectId: 'fetchchat-e0418',
    authDomain: 'fetchchat-e0418.firebaseapp.com',
    storageBucket: 'fetchchat-e0418.firebasestorage.app',
    measurementId: 'G-SD7QFZKTM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCiYi-yUIZDGtOdxYyjaXQg972m-Q8Qrs',
    appId: '1:197181622848:android:9d67ea25b1862f4f786da5',
    messagingSenderId: '197181622848',
    projectId: 'fetchchat-e0418',
    storageBucket: 'fetchchat-e0418.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCikqvsnru0Trmg4nuFA8wwXgaeznTRQTI',
    appId: '1:197181622848:ios:2ce40affffbcffa3786da5',
    messagingSenderId: '197181622848',
    projectId: 'fetchchat-e0418',
    storageBucket: 'fetchchat-e0418.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCikqvsnru0Trmg4nuFA8wwXgaeznTRQTI',
    appId: '1:197181622848:ios:2ce40affffbcffa3786da5',
    messagingSenderId: '197181622848',
    projectId: 'fetchchat-e0418',
    storageBucket: 'fetchchat-e0418.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJg3LEJMFKVEaZf6CYniKKhFWDTQuf40g',
    appId: '1:197181622848:web:a9eeb7d6a402947c786da5',
    messagingSenderId: '197181622848',
    projectId: 'fetchchat-e0418',
    authDomain: 'fetchchat-e0418.firebaseapp.com',
    storageBucket: 'fetchchat-e0418.firebasestorage.app',
    measurementId: 'G-6N97DSESLC',
  );
}
